# Generated by Django 2.2.5 on 2019-10-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_map',
            field=models.CharField(default='\n    ______________________\n    |                    |\n    |                    |\n    |                    |\n    |____________________|\n    ', max_length=3001),
        ),
    ]
